### ISSUE TITLE
Learn RUST programming language

### ISSUE THREAD

**Issue by carlstoker** [uri-csc592-dis-f24/clam#1]
Continue to learn RUST through completing the rustlings course. This was recommended by Prof Daniels as the way for me to learn it the most effectively that I can.

I will be getting additional guidance and practice from Prof Daniels where possible and appropriate.

**Comment by nick-rommel** [comment]
I have learned enough Rust to start working with Carl on the code. I did not finish every module of the Rustlings course, but they are there if  I need additional information. The main point from what I have learned is that I (hopefully) have increased my Rust "literacy" enough where I can read through code successfully now, as well as *know* how to ask the right questions if I get stuck somewhere.
