### ISSUE TITLE
Set up Remote Connection

### ISSUE THREAD

**Issue by nick-rommel** [uri-csc592-dis-f24/clam#7]
Establish remote (ssh) connection from laptop to desktop tower. Will need to enabling port forwarding on my router to do this properly.
-Carl should have more information as the exact specifics, as he seems to have done this before.

**Comment by carlstoker** [comment]
Hey Nick, these articles might be helpful. It's fairly straightforward to set up the ssh server. Setting up port forwarding will depend on your router. Did you say you have a Linksys or TP Link router?  I forget which.

* Setting up ssh: https://www.cyberciti.biz/faq/ubuntu-linux-install-openssh-server/
  * (Optional) a more secure way to login: https://www.digitalocean.com/community/tutorials/how-to-configure-ssh-key-based-authentication-on-a-linux-server
* Port forwarding
  * Linksys: https://support.linksys.com/kb/article/318-en/#single
  * TP Link: https://www.noip.com/support/knowledgebase/setting-port-forwarding-tp-link-router

**Comment by nick-rommel** [comment]
Oh, that's incredibly helpful, thank you! I have a TP link router, so hopefully it will be straight forward.

**Comment by nick-rommel** [comment]
Status Update 11/13/2024:
I have tried for a while to set up the connection, but SSH was not as straight forward as I had thought it would be. I will be regrouping with Carl today and he can give me some additional advice, and at the very least help me get the service set up on my laptop.

**Comment by carlstoker** [comment]
Let's touch base today and see what our next steps should be.

**Comment by carlstoker** [comment]
Touched base with Nick. We
1. enabled his ssh server
2. tested his ability to connect from inside his network
3. enabled port forwarding
4. tested his ability to connect from outside his network
5. generated ssh keys
6. disabled password-based authentication
7. tested his ability to connect when password-based authentication is disabled
8. Set up VS code to connect to his Ubuntu system both inside and outside his network

We did some troubleshooting along the way.  His remote connection setup appears to be complete.
